#!/bin/bash


# general functions

function pause(){
  read -p "$*"
}

function welcome(){
  echo -e "Witaj w instalatorze skina!"
}

function bar(){
  echo "========================================"
}

# login functions

function login(){
  cd /usr/local/directadmin/data/templates/
  rm $login
  wget https://github.com/kexior/da/master/utils/login/login.html
}

# skin functions

function end(){
  bar
  echo "Gratulacje!!, kexiorTheme zosta poprawnie zainstalowany!"
  bar
  echo "Teraz przejdź do DA i"
  echo "1 | Wejdź na konto admina"
  echo "2 | Poziom reseller -> Menadżer szablonów"
  echo "3 | Wybierz kexior :)!"
  bar
  echo "Dziekujemy."
  bar
}

function joinFolder(){
  cd /usr/local/directadmin/data/skins/
}

function install(){
  echo "Instalacja..."
  git clone https://github.com/kexior/da.git
  chown -R diradmin:diradmin kexior/
}

function update(){
  echo "Aktualzizacja..."
  git reset --hard
  git pull
  chown -R diradmin:diradmin *
}

# innit

bar
welcome
bar

joinFolder

directory=kexior
login=./login.html

if [ -d "$directory" ]; then
  echo "Folder kexior już istnieje"
  echo -e "\x1B[31m == UPDATE == \x1B[0m"
  pause 'Kliknij enter, aby zaktualizować.'
  cd $directory/
  update
  # install login template
  login
  
else
  pause 'Kliknij enter, aby rozpoczać instalacje.'
  install
  end
fi

